[package]
name = "finite-wasm"
version = "0.1.0"
edition = "2021"
authors = ["Simonas Kazlauskas <finite-wasm@kazlauskas.me>"]
license = "MIT OR Apache-2.0"
readme = "README.mkd"
repository = "https://github.com/near/finite-wasm"
homepage = "https://github.com/near/finite-wasm"
documentation = "https://docs.rs/finite-wasm"
description = """
Transform your WebAssembly modules to guarantee deterministic limits on time and space resources
made available to the programs.
"""

[lib]
harness = false

[[bin]]
name = "finite-wasm"

[dependencies]
bitvec = "1.0.1"
dissimilar = "1"
wasmparser = "0.90"
wasmprinter = "0.2"
thiserror = "1"
num-traits = "0.2.15"

[dev-dependencies]
walkdir = "2.3.0"
thiserror = "1.0.0"
